
# GET http://localhost:8080/timezone

GET http://localhost:8080/timezone?timezone=America/NewYork

# GET http://localhost:8080/timezone?timezone=Europe/Berlin

# GET http://localhost:8080/addOneHour

